"""initial schema

Revision ID: aa4cb698c68d
Revises: 
Create Date: 2026-06-13 07:18:32.648919

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'aa4cb698c68d'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('email_address', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.Enum('GMAIL', 'OUTLOOK', 'GENERIC', name='providertype'), nullable=False),
    sa.Column('credentials_key', sa.String(length=255), nullable=True),
    sa.Column('imap_host', sa.String(length=255), nullable=False),
    sa.Column('imap_port', sa.Integer(), nullable=False),
    sa.Column('use_ssl', sa.Boolean(), nullable=False),
    sa.Column('sync_enabled', sa.Boolean(), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_cursor', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_address')
    )
    op.create_table('threads',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('subject_base', sa.String(length=500), nullable=False),
    sa.Column('participants_json', sa.Text(), nullable=False),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('last_activity', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_threads_account', 'threads', ['account_id'], unique=False)
    op.create_index('idx_threads_last_activity', 'threads', ['last_activity'], unique=False)
    op.create_table('emails',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('thread_id', sa.String(length=36), nullable=True),
    sa.Column('message_id', sa.String(length=255), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('folder', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=1000), nullable=False),
    sa.Column('sender_name', sa.String(length=255), nullable=False),
    sa.Column('sender_email', sa.String(length=255), nullable=False),
    sa.Column('recipients_json', sa.Text(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('body_text', sa.Text(), nullable=False),
    sa.Column('body_html', sa.Text(), nullable=False),
    sa.Column('has_attachments', sa.Boolean(), nullable=False),
    sa.Column('attachment_names', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('is_starred', sa.Boolean(), nullable=False),
    sa.Column('is_important', sa.Boolean(), nullable=False),
    sa.Column('labels', sa.Text(), nullable=False),
    sa.Column('is_indexed', sa.Boolean(), nullable=False),
    sa.Column('is_analyzed', sa.Boolean(), nullable=False),
    sa.Column('in_reply_to', sa.String(length=255), nullable=False),
    sa.Column('references_json', sa.Text(), nullable=False),
    sa.Column('raw_headers_json', sa.Text(), nullable=False),
    sa.Column('raw_size_bytes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_emails_account', 'emails', ['account_id'], unique=False)
    op.create_index('idx_emails_analyzed', 'emails', ['is_analyzed'], unique=False)
    op.create_index('idx_emails_date', 'emails', ['date'], unique=False)
    op.create_index('idx_emails_folder', 'emails', ['account_id', 'folder'], unique=False)
    op.create_index('idx_emails_indexed', 'emails', ['is_indexed'], unique=False)
    op.create_index('idx_emails_sender', 'emails', ['sender_email'], unique=False)
    op.create_index('idx_emails_thread', 'emails', ['thread_id'], unique=False)
    op.create_table('email_analyses',
    sa.Column('email_id', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('priority_score', sa.Float(), nullable=True),
    sa.Column('spam_score', sa.Float(), nullable=True),
    sa.Column('is_phishing', sa.Boolean(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('action_items', sa.Text(), nullable=False),
    sa.Column('extracted_dates', sa.Text(), nullable=False),
    sa.Column('extracted_entities', sa.Text(), nullable=False),
    sa.Column('suggested_action', sa.String(length=255), nullable=True),
    sa.Column('sentiment', sa.String(length=50), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('prompt_version', sa.String(length=50), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['email_id'], ['emails.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('email_id')
    )
    op.create_table('user_feedback',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email_id', sa.String(length=64), nullable=False),
    sa.Column('field', sa.String(length=100), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['email_id'], ['emails.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_feedback_email_id'), 'user_feedback', ['email_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_feedback_email_id'), table_name='user_feedback')
    op.drop_table('user_feedback')
    op.drop_table('email_analyses')
    op.drop_index('idx_emails_thread', table_name='emails')
    op.drop_index('idx_emails_sender', table_name='emails')
    op.drop_index('idx_emails_indexed', table_name='emails')
    op.drop_index('idx_emails_folder', table_name='emails')
    op.drop_index('idx_emails_date', table_name='emails')
    op.drop_index('idx_emails_analyzed', table_name='emails')
    op.drop_index('idx_emails_account', table_name='emails')
    op.drop_table('emails')
    op.drop_index('idx_threads_last_activity', table_name='threads')
    op.drop_index('idx_threads_account', table_name='threads')
    op.drop_table('threads')
    op.drop_table('accounts')
    # ### end Alembic commands ###
